#ifndef __OAM_BSC_H__
#define __OAM_BSC_H__

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NMIF_SETGET_MSG_LEN 512

/* global operation code defines */
enum
{
    /*common*/
    M2_OPCODE_COMMIN = 0,
    M2_FTPINFO_GET = M2_OPCODE_COMMIN,
    M2_FTPINFO_SET,
    M2_SNTPINFO_GET,
    M2_SNTPINFO_SET,
    M2_SYSINFO_GET,
    M2_SYSINFO_SET,
    M2_TRAPSRVENTRY_GET,
    M2_TRAPSRVENTRY_SET,
    M2_REDUNDANCYINFO_GET,
    M2_REDUNDANCYINFO_SET,
    M2_CFGMAINTAIN_GET,
    M2_CFGMAINTAIN_SET,
    M2_IMAGEMAINTAIN_GET,
    M2_IMAGEMAINTAIN_SET,
    M2_IMAGESTATUSENTRY_GET,
    M2_SYSMANAGE_GET,
    M2_SYSMANAGE_SET,
    M2_NETTOP_GET,
    M2_CPU_GET,
    M2_MEM_GET,
    M2_OPCODE_COMMAX,

    /* ebs*/

    M2_OPCODE_EBSMIN = 1000,
    M2_BSCSYS_GET = M2_OPCODE_EBSMIN,
    M2_BSCSYS_SET,

#if defined (LIB_PDT) || defined (LIB_PSS)

    /* pdtc add by JJ */
    M2_SYSTEMINFO_GET ,
    M2_SYSTEMINFO_SET,
    M2_ACCESSPARAMETERS_GET,
    M2_ACCESSPARAMETERS_SET,
    M2_TRAFFICCHANNELPARAMETERS_GET,
    M2_TRAFFICCHANNELPARAMETERS_SET,
    M2_RESELECTIONPARAMETERS_GET,
    M2_RESELECTIONPARAMETERS_SET,
    M2_LLCPARAMETERS_GET,
    M2_LLCPARAMETERS_SET,
    M2_ROAMINGPARAMETERS_GET,
    M2_ROAMINGPARAMETERS_SET,
#else
    M2_BSCSRVCELLSYSINFO_GET,
    M2_BSCSRVCELLSYSINFO_SET,
    M2_BSCSRVCELLACCESSPARAM_GET,
    M2_BSCSRVCELLACCESSPARAM_SET,
    M2_BSCSRVCELLTRAFFICCHAN_GET,
    M2_BSCSRVCELLTRAFFICCHAN_SET,
    M2_BSCSRVCELLRESELECTPARAM_GET,
    M2_BSCSRVCELLRESELECTPARAM_SET,
    M2_BSCSRVCELLCARRIERPARAM_GET,
    M2_BSCSRVCELLCARRIERPARAM_SET,
    #endif
    M2_SYNCBSENTRY_GET,
    M2_SYNCBSENTRY_SET,
    M2_SYNCBSINFO_GET,
    M2_SYNCBSINFO_SET,
    M2_INTERFERENCEDETECT_GET,
    M2_INTERFERENCEDETECT_SET,
    M2_JAMDETECT_GET,
    M2_JAMDETECT_SET,
    M2_DOWNLINKJAMTHRESHOLD_GET,
    M2_DOWNLINKJAMTHRESHOLD_SET,
    M2_CPUTHRESHOLD_GET,
    M2_CPUTHRESHOLD_SET,
    M2_INTCARRIER_GET,
    M2_INTCARRIER_SET,
    M2_GPSTSCCSWHPAR_GET,
    M2_GPSTSCCSWHPAR_SET,
    M2_BSRCFG_GET,
    M2_BSRCFG_SET,
    M2_BSCSYS1_GET,
    M2_BSCSYS1_SET,
    M2_BSRENTRY_GET,
    M2_BSRENTRY_SET,
    M2_CHANNELENTRY_GET,
    M2_CHANNELENTRY_SET,
    M2_MXLIUIDENTRY_GET,
    M2_MXLIUIDENTRY_SET,
    M2_FREQDENTRY_GET,
    M2_FREQDENTRY_SET,
    M2_SYNCBSMXLIUIDENTRY_GET,
    M2_SYNCBSMXLIUIDENTRY_SET,
    M2_BSNETTOPENTRY_GET,
    M2_NETTOPBSCENTRY_GET,
    M2_NETTOPBSRENTRY_GET,
    M2_NETTOPPSMENTRY_GET,
    M2_NETTOPSLAENTRY_GET,
    M2_NETTOPDPXENTRY_GET,
    M2_NETTOPXHUBENTRY_GET,
    M2_NETTOPENV_GET,
    M2_NETTOPBSEXENTRY_GET,
    M2_NETTOPPSCENTRY_GET,
    M2_NETTOPBSRMENTRY_GET,
    M2_NETTOPBS04DENTRY_GET,
    M2_OPCODE_EBSMAX,

    M2_OPCODE_GISMIN = 4000,
    M2_COMMCFG_GET = M2_OPCODE_GISMIN,
    M2_COMMCFG_SET,
    M2_OPCODE_GISMAX,
};


typedef enum
{
    CURRENT_ROW = 0,    /* request current row */
    FIRST_ROW,          /* request first row as default */
    NEXT_ROW            /* request next row */
}AGENT_ROW_CURSOR;

#define ROWSTATUS_ACTIVE            1
#define ROWSTATUS_NOTINSERVICE      2
#define ROWSTATUS_NOTREADY          3
#define ROWSTATUS_CREATEANDGO       4
#define ROWSTATUS_CREATEANDWAIT     5
#define ROWSTATUS_DESTROY           6

/* fnmp agent callback function type
* opCode: indicate M2_XXX_GET, M2_XXX_SET
* optInd: when M2_XXX_GET this means FIRST_ROW, CURRENT_ROW or NEXT_ROW
*           when M2_XXX_SET this indicates which nodes to be set
* pData: pointer for mib structure;
* result: used to set process result, NO_ERROR ,NO_SUCH_NAME, COMMIT_FAILED
********************/

/*snmp agent module init function */
EINT32 agentRbLibInit(void);


/*
trapReport: 告警发送函数
trapType: 告警类型
modType: 模块类型
modId: 模块ID
msgCode: 告警码
level: 告警等级
CauseNumber: 告警原因
subModType: 告警子模块类型
subModId: 子模块ID
argc: 附加参数格式
return: 正确放回 ETOK，错误返回 ETERROR
*/
int trapReport(ET_TRAP_TYPE trapType, ET_TRAP_MODULETYPE modType,EINT32 modId,
                    EINT32 msgCode,  ET_TRAP_LEVEL level, EINT32 CauseNumber,
                    ET_TRAP_SUBMODULETYPE subModType, EINT32 subModId, EINT32 argc, ...);

#ifdef __cplusplus
}
#endif

#endif /* __OAM_BSC_H__ */

